### ISSUE TITLE
Negative values for cells that shouldn't be negative

### ISSUE THREAD

**Issue by mesotron** [getguesstimate/guesstimate-app#1002]
S1L is a lognormal distribution ranging from .0001 to .1. Therefore it should be impossible for 1 - (1 - S1L)^10 to be negative, but this produces highly negative values. Is this a bug, or am I just missing something basic? See https://www.getguesstimate.com/models/13434 .

![distributions](https://user-images.githubusercontent.com/373702/59468529-332f0180-8e2a-11e9-9416-7e9983abefde.png)

**Comment by OAGr** [comment]
When it says "0.0001 to 0.1", that's the 90th percentiles; some numbers are outside that range.
What's happening here is that there are 1-2 outliers or so that are over 1.0 I think, then when they are raised to the ^10 power get pretty huge. 

One way around this is with the ``=filterGreaterThan`` command. You can do ``=filterGreaterThan(S1L,1)`` or similar to remove the few outliers greater than 1.

**Comment by mesotron** [comment]
Looks like that's exactly it. Thanks so much for your help.
