### ISSUE TITLE
Small sample count for powers

### ISSUE THREAD

**Issue by OAGr** [getguesstimate/guesstimate-app#133]

**Comment by OAGr** [comment]
![image](https://cloud.githubusercontent.com/assets/377065/13481025/0b46afc2-e097-11e5-8c3a-78b436565cd5.png)

**Comment by yalla** [comment]
Related: The same happens when you use the log() function. Figured this out while toying around with Exponential and Weibull distributions; the former uses log(), the latter pow().
![screenshot from 2016-03-05 06-17-42](https://cloud.githubusercontent.com/assets/350047/13545865/1f5677a4-e29a-11e5-9d43-dfd9291d62ea.png)

**Comment by OAGr** [comment]
This seems like it's no longer an issue, please correct if I'm wrong here.
