### ISSUE TITLE
std() and var() always 0

### ISSUE THREAD

**Issue by yalla** [getguesstimate/guesstimate-app#141]
Tried to use the std() and var() functions from math.js, but the result is always 0.0.
This applies to manual data, normal distributions, uniform distributions and constants.
Some other functions might be affected as well, but I didn't try them all.
Example model: https://www.getguesstimate.com/models/4288

**Comment by OAGr** [comment]
This makes sense in accordance to what the math is doing.  When you write a function, it gets applied 5000 times for random samples of the input, it does not get applied to the entire set of inputs. So ``std(AB)`` would be applied 5000 times with single values, rather than one time with 5000 values.  This could hypothetically be useful if you wanted to find the ``std`` of values from a few different nodes or a very small set of custom data, but I understand it's confusing.

What would be useful soon would be to have some way of being able to specify that something targets a full set of samples instead of individual samples.  That is a different issue though; an enhancement instead of a bug.  I'll file that separately.
