### ISSUE TITLE
Private models (Discussion)

### ISSUE THREAD

**Issue by optilude** [getguesstimate/guesstimate-app#75]
Hi,

This is really great and I'd like to start using it for all sort sort of things. However, it can be difficult to use it if models are all public (unless I'm missing something).

Ideally, we'd have SSL (you can use https://letsencrypt.org/ for free certs) and a flag to make models public or private. Some kind of sharing system ("let use X see this model") would be nice, but not critical.

Alternatively, I was going to self-host but this doesn't really seem possible at the moment because the Rails app isn't yet published (by the way: publish it; until you do it's pretty hard to get more contributors working on the app, and even if it's not perfect, others will help you make it better), and even in "remote API" mode I can't get it to build on my Mac (npm install fails with "No compatible version found: lodash._charsendindex@'>=3.0.0 <4.0.0'").

I'm going to keep trying to make it work locally and see if I can help implement private models, but it's a bit "catch 22" at the moment.

Thanks for doing this and thanks for sharing. It's a really impressive thing you've built!

**Comment by OAGr** [comment]
Hi Optilude,

Thanks for your thoughts here.

You are correct, models are currently only public.  The last few days for me have been working on support requests / stability / talking with users, at this point I will work to make sure that happens.

One challenging thing is that this is costing quite a bit right now (all my time, much of my money).  I have had people & businesses asking to pay for it.  One natural place would be for businesses to pay for private models.  Perhaps the first 1-3 private models would be free, others paid, for instance.  Before launch I didn't expect there to be much interest, but was hoping to eventually turn it into a business; now It's my main plan.

Going forward I want to figure out a way to keep the mathematics and UI parts in this package open source, while splitting off some of the payments and more business-focussed sections.  For one thing, I imagine most people who self-host wouldn't want to set up the entire system (including Stripe accounts and so on).  I envision a system like Github, where git is open source, but Github has a lot of infrastructure around it that's not (of course in this case it's a bit different because the 'git' here doesn't yet exist.)

I don't want to set up the expectation that I'm going to be spending a large amount of my time focussed on a self-hosted version for the indefinite future.  I don't have a lot more money, and also would like to see this go much further than I imagine it would if it were completely open source.

**Comment by optilude** [comment]
Hi,

It's really cool that you are so transparent.

Guesstimate has attracted a lot of interest. I would guess that within that is a small number of people who need it and have the skills to help improve it and would want to do that.

In my experience, you need a small amount of investment to reduce the inertia for that. GitHub (check), maybe some real time chat (gitter?), maybe a forum/mailing list, and definitely just enough docs about how the code builds and how you want people to work with it (standards, key design decisions...).

Right now, if you just run npm install, it doesn't build (at least not for me), which means spending time debugging obscure build issues instead of finding more meaningful contributions.

Maybe no one will send any useful PRs, but maybe someone will. If you are making money out of this, that's improvements you don't pay for except through some investment in lowering inertia and some management overhead.

If you want to make this into a company, that is of course also a really big job. You certainly have the talent to build something good enough and there certainly is a lot of interest. Whether it is saleable at a price that is viable I really couldn't tell you. Excel is a really hard product to dislodge. I would certainly start simple in terms of commercialisation and keep other options open until you figure out whether it's viable.

If the core product is open source and stays open in a meaningful way (so others can indeed contribute) then it will always have a life regardless of whether a commercial venture turns out to be a success. It sounds like a very good idea to architect the proprietary bits around payment etc as plugins or integrations that are optional, because those won't be interesting in an open source sense. The thing just had to build / work standalone enough so that if people have an interest then they will be able to run it and use it.

I look forward to seeing how this product evolves and hopefully to have a chance to contribute to it in some tiny way. Would I pay a lot for it with its current feature set? Probably not because I might only use it once or twice a month, but a few tens of dollars a year I'd find. 

Martin

**Comment by OAGr** [comment]
Hi,

Great to hear that, that all sounds quite reasonable. 

I added a Gitter channel.  https://gitter.im/getguesstimate.  I intend on setting up a forum soonish (I was thinking Discourse, curious if people prefer Flarum or similar).

Getting 'npm install' to work fine is a surprisingly large hassle.  It has been improved somewhat, but is still a pain.  I'd like to spend time here, but it will take a while.  It should work if you fiddle with it enough, but it's not all too much fun.  If anyone here is great with npm dependencies, this would be something that would be very valuable to improve on.

The trick for open source is going to be finding time-efficient ways on my end to make it both useable for personal hosting / use, and also useable in a paid app.  This isn't trivial, I'll give it a lot of thought (and be open to ideas of course).

One nice thing about it being paid is that if there is money, this will help ensure the project will live much longer.  I'd also be happy to give free coupon codes to open source contributors around the project :)  Imagine most real money will come from larger businesses.

**Comment by OAGr** [comment]
I've fixed some of the issues with the server, put that online.  https://github.com/getguesstimate/guesstimate-server

It should all work now, though if you want to make models, it would still require some work.  You need to set up auth0, algolia, and postgres to have it all working.

It's set up with an existing dev algolia and auth0 environment for development.

**Comment by optilude** [comment]
Brilliant, thanks!

**Comment by OAGr** [comment]
We have private models now in the paid plans.  Closing.
