### ISSUE TITLE
Support double-triangular distribution for software estimation

### ISSUE THREAD

**Issue by StephenTung-CR** [getguesstimate/guesstimate-app#829]
Ozzie, 

I absolutely love what you guys are doing. Keep it up!

I wish that guestimate can help me estimate software features using the three-point estimation and double-triangular distribution:

http://gonzaloserrano.io/clean-code-and-software-estimation/

https://en.wikipedia.org/wiki/Three-point_estimation

http://www.mhnederlof.nl/doubletriangular.html

Is this something we can do?

**Comment by mmcdermott** [comment]
Hi Stephen, 

Unfortunately, right now we don't support the double triangular distribution. We'll work on adding that. In the meantime, there are some workarounds you might consider. First, some of our users have used [Weibull Distributions](https://en.wikipedia.org/wiki/Weibull_distribution) in the past to model [software engineering features](https://www.getguesstimate.com/models/923). 

Second, you can also build up to that distribution out of lower level distributions. It's a bit sketchy, but it works as well. Here's an example: https://github.com/getguesstimate/guesstimate-server/pull/172

Regardless, we'll work to add this distribution type. Thanks for the feedback!

**Comment by yalla** [comment]
Good Morning Steven,

just yesterday I had the same idea, tried implementing it myself with given distributions, thought "whatever" (`0 < x < F(c) ? func1 : func2` didn't work out) and went for the right thing and made up a straight implementation of the PERT-distribution. Yeah, it's a little cumbersome, but works just fine since it's a modified beta distribution:
https://www.getguesstimate.com/models/7116

The rationale behind PERT is:
1. Non-experts give minimum and maximum time;
2. An experts give the most likely time called the mode;
3. Add a variable lambda, which is traditionally 4;
4. Magic.

I used PERT in the past for task estimations to check if my Scrum team's estimations could be improved and it worked out quite ok. Not exact, but how could a model ever represent exact values anyway...

Hope that helps,
Alex.

**Comment by mmcdermott** [comment]
Hi @yalla  & @StephenTung-CR 

We've gone ahead and added both the double triangular distribution and the wikipedia-defined beta PERT distribution as properly supported distributions. To use them, the syntax is:
`=doubleTriangular(min, max, mode)` (mode has a default value of `mean(min, max)`)
and
`=pert(min, max, mode, lambda)` (lambda has a default value of 4, mode has a default value of `mean(min, max)`)
