### ISSUE TITLE
Discussion: What do you want to get out of open source hosting?

### ISSUE THREAD

**Issue by OAGr** [getguesstimate/guesstimate-app#94]
I want to keep most of Guesstimate open source, but there are a lot of different ways of doing that.  On one hand we could try to make it very modular and release each component for independent use; on the other we could focus more on making one large platform for others to host.

Rather than guess what would be best for everyone, I'd appreciate if anyone interested in using the codebase would comment with what they want to use or see it for.  

On my end, I have recently registered a corporation for Guesstimate and am in the process of monetizing it.  I have a pretty ambitious idea of where I would like it to go, and want it to be self sustaining to help get there.  I've started to add private functionality and will start working on payment functionality.

While I'm fine with someone else taking the codebase and using it for personal use (or taking small parts of it for business use, preferably non-competing businesses), I'm hesitant to make it easy for others to use this codebase to directly sell the same thing.  It also seems like having the payment functionality be part of the codebase would make it more difficult for people who want to use it for personal use to do so.  In the future I'll try to keep the payment aspects separate, and some of those will be proprietary (though not very interesting).

**Comment by yalla** [comment]
As always with FOSS licenses, there is no contradiction in monetizing. The usual business models are offering...
* managed services
* professional services
* premium software modules not bundled with the "community edition"
...and any combination of these.

Look, for example, at RStudio Server. They offer a community edition which is free to use. They also sell commercial versions which include support and additional features.
From another point of view, a ecosystem can develop around it. If I weren't completly occupied with my day-job I'd probably start running a company offering RStudio-Server as a service. Companies or individuals could rent RStudio server instances I'd be running on my machines and I'd set up a prizing model which could charge for storage, CPU time, transferred data or any other combination. For a little more I could be offering professional services and sell of my R-skills to help customers implementing what they want.
A bigger company could even be selling RStudio Server appliances.

The thing is, you picked the MIT license, so anyone can build on your work and monetize it in the same way. You could as well use different licenses which you force that same license upon people building on your work so that you can use their work in your commercial products. The most famous example would be the viral aspect of the GPL.

But then again you need to take into account that the FOSS spirit encourages everyone to take the code, use it for any purpose, modify and redistribute these modifications. These are commonly known as the four freedoms: Use, study, share, improve (compare https://fsfe.org/freesoftware/basics/4freedoms.en.html )

I get your point that you wouldn't necessarily like it that others would offer the same kind of service as you, but the business model would concentrate on the things which make you, the original author, unique.

If I were you I'd be doing it like this:
* keep the source open
* create a prizing model (for instance "free tier", "individual tier with export and private option", "commercial tier with support & SLAs", on top of that professional service charged by the hour/day or a fixed price
* do a basic calculation with several cloud providers so that you can offer dedicated servers to keep the models really private
* ...add your own idea.

I could be writing a lot more, so if you have any questions, drop me a line :-)

Alex.

(Full disclosure: I'm a fellow of the Free Software Foundation Europe as well as a consultant in my day job)

**Comment by OAGr** [comment]
Thanks for the response Alex,

I think we mostly agree here.  I'm not planning on ever taking any code that is under MIT license and making it anything else, for one because that isn't allowed by the license (and wouldn't make sense anyway).  Also prefer MIT to GPL.

The analogy to Rstudio makes sense.  I see Guesstimate as a company effectively selling the hosting of the Guesstimate tool.  With Rstudio; the tool is open source, but specific hosting features I imagine are not.

This is basically what I meant above when I said 'I'm hesitant to make it easy for others to use this codebase to directly sell the same thing'.  Right now I'm writing code to host & charge for Guesstimate, and I expect some of this code eventually not to have the MIT license.  For the Rstudio analogy; if you wanted to sell a service to host Rstudio, I imagine you would be responsible for making the sales website and setting up the infrastructure; you wouldn't download a service to do just this and then put it online and start selling it.
