### ISSUE TITLE
Interval entry in "A-B" format rather than "[A,B]"

### ISSUE THREAD

**Issue by jtbandes** [getguesstimate/guesstimate-app#99]
As a new user I tried to enter an interval by typing `A-B`, which didn't work, and in fact silently did something else (I think the `-B` part is ignored).

**Comment by OAGr** [comment]
What would you think about **a:b**?  I want to change this at some point, but want to get it right when we do.

One downside about 'A-B' is that it could imply 'A minus B', which is what it would be if it were a function.

Also, there's the big question of how this could be extended to other asymmetric distributions.  One possibility would be:
[0,50,300] or 0:50:300 or 0-50-300, indicating a 5% at 0, a 50% at 50, and a 95% at 300.

**Comment by jtbandes** [comment]
I think there's a *lot* of room for exploring different designs here. The most appropriate/expedient first pass would probably be to fix the bug that `A-B` is accepted as input but does nothing useful.

**Comment by jtbandes** [comment]
To be clear, entering `1-3` is currently treated the same as `1`. IMO it should be a syntax error, or should be the same as `-2`.

**Comment by mmcdermott** [comment]
I would say that as we currently only support functions when prefixed with '=' accepting 1-3 as a range from 1 to 3 seems appropriate. And I think it would be intuitive to most when they hear 'enter a range' 1-3-5 as an asymmetric range though feels strange to me. Perhaps a more involved syntax for that? We also need to capture the intuitive use cases for those asymmetric ranges a bit better, I think, to understand how to capture them in input.

**Comment by mmcdermott** [comment]
Another option would be 1-3 vs [1,3] as differing default types. My brain wants to subtly think that 1-3 is a uniform and [1,3] is a normal, but that may just be bias.

**Comment by jtbandes** [comment]
I think all these options are probably too non-obvious for new users. You might want to consider the direction of more-GUI text entry for ranges. At the very least, you could have a set of radio buttons for picking normal/uniform/constant value/etc.

**Comment by OAGr** [comment]
My guess is that we'll need both a GUI and a text input.  I love not needing a GUI for most things (and most values are pretty simple, at least ones I put in), but definitely realize more specificity would be nice.

**Comment by yalla** [comment]
I'm torn here regarding the syntax, but then again I'm spoiled by other tools. I'm used to write `rnorm(100, mean=5, sd=2)` or `rpois(100, lambda=5)` and whatever else. The `[a,b]` syntax has it's beauty in that it's using confidence intervals implicitly, but if you start enhancing it to `[a,b,c]` for asymmetric distributions, it get's kinda sketchy... sure, you could say "it'll always be 5,50,95% by definition". You have several different distributions on your roadmap anyway, why not just says that you stick with the current `[a,b]` syntax for normal distribution and go for something like `P[lambda,k]` for Poission, `N[mu,alpha,beta]` for the general normal distribution... because then there's also a place for syntactic sugar like `[a,b,c]`.

**Comment by OAGr** [comment]
Agreed there could be a collection of types; sugar shorthand, and longer versions.
